default: &default
  adapter: postgresql
  database: freetrade_prod
  pool: 5
  host: localhost
  timeout: 5000

development:
  <<: *default
  database: freetrade_dev

test:
  <<: *default
  database: freetrade_test

production:
  host: <%= ENV["DATABASE_URL"] %>
